version: "3.8"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
     - "3000"
    volumes:
     - ./mariadb:/docker-entrypoint-initdb.d:ro
  server:
    build: ./apacheserver
    restart: always
    volumes:
     - ./apacheserver:/usr/local/apache2/htdocs/
    ports:
     - "8080:80"